[package]
name = "turtlebot"
version = "0.1.0"
authors = ["scturtle <scturtle@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.14"
log = "0.4"
env_logger = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.3"
chrono = "0.4"
chrono-tz = "0.5"
rss = "1.0"
atom_syndication = "0.6"
feedfinder = "0.1"
url = "1.7"
runtime = "0.3.0-alpha.7"
isahc = { version = "0.7.1", features = ["json"] }
http = "0.1"
rusqlite = { version = "0.20", features = ["chrono"] }
