[package]
name = "turtlebot"
version = "0.1.0"
authors = ["scturtle <scturtle@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"
log = "0.4.6"
env_logger = "0.6.1"
failure = "0.1.5"
failure_derive = "0.1.5"
reqwest = "0.9.15"
diesel = "1.4.2"
tokio = "0.1.19"
futures = "0.1.26"
serde_json = "1.0.39"
hyper = "0.12.28"
