[package]
name = "turtlebot"
version = "0.1.0"
authors = ["scturtle <scturtle@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13"
log = "0.4"
env_logger = "0.6"
failure = "0.1"
failure_derive = "0.1"
reqwest = "0.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio = { version = "0.1", features = ["async-await-preview"] }
tokio-async-await = "0.1"
futures = "0.1"
lazy_static = "1.3"
diesel = { version = "1.4", features = ["sqlite", "chrono"] }
chrono = "0.4"
chrono-tz = "0.5"
