[package]
name = "turtlebot"
version = "0.1.0"
authors = ["scturtle <scturtle@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13"
log = "0.4"
env_logger = "0.6"
failure = "0.1"
failure_derive = "0.1"
reqwest = "0.9"
diesel = "1.4"
tokio = "0.1"
futures = "0.1"
serde_json = "1.0"
hyper = "0.12"
lazy_static = "1.3"
